import Header from '@/components/Header';
import Container from '@/components/ui/container';
import { routes } from '@/routes';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Toaster } from 'sonner';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});

const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const navItems = [
  {
    label: 'Home',
    href: routes.home,
  },
  {
    label: 'Devices',
    href: routes.devices.list,
  },
  {
    label: 'Customers',
    href: routes.customers.list,
  },
  {
    label: 'Service Orders',
    href: routes.serviceOrders.list,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Container>
          <Header links={navItems} />
          {children}
        </Container>
        <Toaster richColors />
      </body>
    </html>
  );
}
